# Generated by Django 5.1.1 on 2026-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_id_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('Matematica', 'Matematica'), ('Informatica', 'Informatica')], default='Matematica', max_length=20),
        ),
    ]
