import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowRight, Download, FileText } from 'lucide-react';
import PageTransition from '../components/PageTransition';
import SEO from '../components/SEO';
import { breadcrumbSchema } from '../seo/structuredData';
import {
  CATEGORY_LABEL,
  CATEGORY_ORDER,
  RESOURCES,
  SUBJECT_LABEL,
  resourceHref,
  resourcesForCategory,
} from '../config/resources';
import type { Resource } from '../config/resources';
import { resourceBytes } from '../content/resources.generated';

/**
 * /resurse — the downloads listing.
 *
 * TWO ACTIONS PER GUIDE, BOTH SPELLED OUT. The first version made the whole
 * row a single `download` anchor with a small "Descarcă" label in the margin:
 * you could not tell the rows were files, and there was no way to look inside
 * one before committing to a download. A 88-page guide is a reading decision,
 * so "Citește în browser" (a plain link — the PDF renders in the browser's
 * viewer) sits next to "Descarcă PDF" (the same URL with `download`). Nothing
 * is server-side: `Content-Disposition: attachment` would force a save in
 * every context, including a link someone shares.
 *
 * NO FILTER STATE. The materials are grouped into static sections by
 * category rather than filtered in React. The site is prerendered with
 * Playwright, and a filter that unmounts non-matching entries would bake only
 * the default subset into the HTML a crawler reads — the same failure that
 * shipped six missing FAQ answers. Every entry is in the DOM on first paint.
 *
 * NO HAND-TYPED SIZES. `resourceBytes` is generated by build-content.mjs from
 * the files themselves; a size here can never disagree with what downloads.
 *
 * The files are served from /descarcari/, not from under /resurse — see
 * docs/DOWNLOADS-SECTION.md §3.1 for why the two paths are kept apart.
 */

/**
 * Romanian decimal comma, and KB below a megabyte — "0,6 MB" tells a student
 * less than "599 KB" does. Undefined is possible only if the generated module
 * is stale relative to the manifest, which the build guard prevents; rendering
 * nothing is still better than rendering "NaN".
 */
const formatSize = (bytes: number | undefined): string | null => {
  if (!bytes) return null;
  const kb = bytes / 1024;
  if (kb < 1024) return `${Math.round(kb)} KB`;
  return `${(kb / 1024).toFixed(1).replace('.', ',')} MB`;
};

const ResourceRow: React.FC<{ resource: Resource; index: number }> = ({ resource, index }) => {
  const size = formatSize(resourceBytes[resource.slug]);
  const href = resourceHref(resource);

  // Every guide's actions read "Descarcă PDF" / "Citește în browser", so the
  // accessible name has to carry the title — otherwise a screen reader's link
  // list is fourteen identical entries.
  return (
    <motion.article
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.08 + index * 0.06 }}
      className="border-b border-[#222] py-9 md:py-11"
    >
      <div className="grid grid-cols-1 md:grid-cols-12 gap-5 md:gap-8">
        {/* Margin metadata — subject first, then what the file physically is. */}
        <div className="md:col-span-3 flex flex-row md:flex-col gap-4 md:gap-2 items-baseline">
          <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#e8734a]">
            {SUBJECT_LABEL[resource.subject]}
          </span>
          <span className="inline-flex items-center gap-2 font-mono text-[10px] tracking-[0.15em] uppercase text-[#999] whitespace-nowrap">
            <FileText size={12} strokeWidth={2} className="shrink-0 text-[#777]" aria-hidden />
            PDF
            {resource.pages ? ` · ${resource.pages} pagini` : ''}
            {size ? ` · ${size}` : ''}
          </span>
        </div>

        <div className="md:col-span-9">
          <h3 className="font-display font-semibold text-2xl sm:text-3xl md:text-[2rem] text-[#f0f0f0] leading-[1.15] tracking-tight mb-3 text-balance">
            {resource.title}
          </h3>
          <p className="text-[0.95rem] text-[#a8a8a8] leading-relaxed max-w-2xl mb-7">
            {resource.description}
          </p>

          {/* Both actions point at the same URL. The only difference is the
              `download` attribute, which is what turns a preview into a save. */}
          <div className="flex flex-col sm:flex-row gap-3">
            <a
              href={href}
              download
              aria-label={`Descarcă PDF: ${resource.title}`}
              className="inline-flex items-center justify-center gap-3 bg-[#e8734a] hover:bg-[#f08c5a] text-[#0a0a0a] px-6 py-3.5 font-mono text-[11px] tracking-[0.2em] uppercase font-medium transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08c5a] focus-visible:ring-offset-2 focus-visible:ring-offset-[#0a0a0a]"
            >
              <Download size={14} strokeWidth={2.5} className="shrink-0" aria-hidden />
              Descarcă PDF
            </a>
            <a
              href={href}
              target="_blank"
              rel="noopener"
              aria-label={`Citește în browser: ${resource.title}`}
              className="inline-flex items-center justify-center gap-3 border border-[#333] hover:border-[#e8734a]/70 text-[#ccc] hover:text-[#f0f0f0] px-6 py-3.5 font-mono text-[11px] tracking-[0.2em] uppercase font-medium transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08c5a] focus-visible:ring-offset-2 focus-visible:ring-offset-[#0a0a0a]"
            >
              Citește în browser
            </a>
          </div>
        </div>
      </div>
    </motion.article>
  );
};

const Resources: React.FC = () => {
  const count = RESOURCES.length;

  return (
    <PageTransition>
      <SEO
        title="Resurse gratuite — ghiduri de matematică pentru BAC, Evaluarea Națională și gimnaziu | AlgoMate"
        description="Ghiduri gratuite în PDF la matematică — Bacalaureat M1, Evaluarea Națională și materia de clasa a VII-a: teorie esențială, probleme rezolvate pas cu pas și modele de subiect. Fără cont și fără adresă de e-mail."
        path="/resurse"
        jsonLd={breadcrumbSchema([{ name: 'Resurse', path: '/resurse' }])}
      />
      <div className="min-h-screen text-[#f0f0f0] pt-24 md:pt-28 pb-20 md:pb-24">
        <div className="max-w-6xl mx-auto px-6">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="mb-12 md:mb-14"
          >
            <div className="flex items-baseline gap-3 md:gap-4 mb-6 md:mb-8">
              <span className="font-mono text-[10px] md:text-[11px] tracking-[0.2em] md:tracking-[0.3em] text-[#e8734a] uppercase whitespace-nowrap">
                § AlgoMate / Resurse
              </span>
              <span className="h-px flex-1 bg-gradient-to-r from-[#333] via-[#222] to-transparent" />
              <span className="font-mono text-[10px] md:text-[11px] tracking-[0.25em] md:tracking-[0.3em] text-[#666] uppercase hidden md:inline">
                {count} {count === 1 ? 'ghid' : 'ghiduri'}
              </span>
            </div>

            <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-5 md:gap-6">
              <h1 className="font-display font-semibold text-[3rem] sm:text-6xl md:text-7xl text-[#f0f0f0] leading-[1.02] tracking-tight">
                Resurse<em className="italic text-[#e8734a] font-normal">.</em>
              </h1>
              <p className="font-mono text-[11px] md:text-xs text-[#888] md:max-w-xs uppercase tracking-wider leading-relaxed">
                → Ghiduri complete, pe subiecte, în PDF.
              </p>
            </div>
          </motion.div>

          {/* The terms and the mechanics, stated once. Nothing here asks for an
              e-mail address, and the two ways to open a guide are named before
              the reader meets the first pair of buttons. */}
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.15 }}
            className="max-w-2xl text-[0.98rem] leading-relaxed text-[#a8a8a8] mb-14 md:mb-16"
          >
            Ghidurile sunt gratuite și se deschid direct — fără cont, fără formular și fără
            adresă de e-mail. Pe fiecare ai două variante:{' '}
            <span className="text-[#f0f0f0]">citește-l în browser</span>, dacă vrei doar să
            arunci un ochi, sau{' '}
            <span className="text-[#f0f0f0]">descarcă-l ca PDF</span>, ca să-l ai la tine și
            offline.
          </motion.p>

          {count === 0 ? (
            <div className="border-y border-[#222] py-20 text-center">
              <p className="text-lg text-[#999]">Primele materiale sunt în pregătire.</p>
              <Link
                to="/blog"
                className="group/link inline-flex items-center gap-3 mt-8 font-mono text-[10px] tracking-[0.3em] uppercase text-[#e8734a] pb-2 border-b border-[#e8734a]/20 hover:border-[#e8734a]/80 transition-all duration-300"
              >
                Între timp, citește subiectele rezolvate
                <ArrowRight
                  size={12}
                  strokeWidth={2.5}
                  className="group-hover/link:translate-x-1 transition-transform"
                />
              </Link>
            </div>
          ) : (
            CATEGORY_ORDER.map((category) => {
              const items = resourcesForCategory(category);
              if (!items.length) return null;

              return (
                <section key={category} className="mb-16 md:mb-20 last:mb-0">
                  <div className="flex items-baseline gap-4 mb-2">
                    <h2 className="font-mono text-[11px] tracking-[0.3em] uppercase text-[#aaa]">
                      {CATEGORY_LABEL[category]}
                    </h2>
                    <span className="h-px flex-1 bg-[#222]" />
                    <span className="font-mono text-[10px] tracking-[0.25em] uppercase text-[#666]">
                      {items.length}
                    </span>
                  </div>

                  <div className="border-t border-[#222]">
                    {items.map((resource, idx) => (
                      <ResourceRow key={resource.slug} resource={resource} index={idx} />
                    ))}
                  </div>
                </section>
              );
            })
          )}

          {/* Closing CTA — the page is free material, but it is also the top of
              the funnel for the thing that is not free. */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="mt-20 md:mt-24 border-t border-[#222] pt-10 flex flex-col md:flex-row md:items-end md:justify-between gap-6"
          >
            <p className="max-w-xl text-[0.98rem] leading-relaxed text-[#a8a8a8]">
              Ghidurile acoperă teoria și exercițiile de bază. Pentru explicații pe punctele
              unde te blochezi și pentru un plan de pregătire pe măsura examenului tău, vino la
              o ședință.
            </p>
            <Link
              to="/inscriere"
              className="group/link inline-flex items-center gap-3 font-mono text-[10px] tracking-[0.3em] uppercase text-[#e8734a] pb-2 border-b border-[#e8734a]/20 hover:border-[#e8734a]/80 transition-all duration-300 whitespace-nowrap self-start md:self-auto"
            >
              Rezervă o ședință
              <ArrowRight
                size={12}
                strokeWidth={2.5}
                className="group-hover/link:translate-x-1 transition-transform"
              />
            </Link>
          </motion.div>
        </div>
      </div>
    </PageTransition>
  );
};

export default Resources;
