import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowRight, Download, FileText } from 'lucide-react';
import PageTransition from '../components/PageTransition';
import SEO from '../components/SEO';
import { breadcrumbSchema } from '../seo/structuredData';
import {
  CATEGORY_LABEL,
  CATEGORY_ORDER,
  RESOURCES,
  SUBJECT_LABEL,
  resourceHref,
  resourcesForCategory,
} from '../config/resources';
import type { Resource, ResourceCategory } from '../config/resources';
import { resourceBytes } from '../content/resources.generated';

/**
 * /resurse — the downloads listing.
 *
 * TWO ACTIONS PER GUIDE, BOTH SPELLED OUT. The first version made the whole
 * row a single `download` anchor with a small "Descarcă" label in the margin:
 * you could not tell the rows were files, and there was no way to look inside
 * one before committing to a download. A 88-page guide is a reading decision,
 * so "Citește în browser" (a plain link — the PDF renders in the browser's
 * viewer) sits next to "Descarcă PDF" (the same URL with `download`). Nothing
 * is server-side: `Content-Disposition: attachment` would force a save in
 * every context, including a link someone shares.
 *
 * NO FILTER STATE. The materials are grouped into static sections by
 * category rather than filtered in React. The site is prerendered with
 * Playwright, and a filter that unmounts non-matching entries would bake only
 * the default subset into the HTML a crawler reads — the same failure that
 * shipped six missing FAQ answers. Every entry is in the DOM on first paint.
 *
 * The jump bar below follows the same rule. It is a list of ordinary in-page
 * anchors, so it works in the prerendered HTML with no JavaScript at all; the
 * IntersectionObserver only adds the "you are here" highlight on top of that.
 * Nothing it does gates content.
 *
 * NO HAND-TYPED SIZES. `resourceBytes` is generated by build-content.mjs from
 * the files themselves; a size here can never disagree with what downloads.
 *
 * The files are served from /descarcari/, not from under /resurse — see
 * docs/DOWNLOADS-SECTION.md §3.1 for why the two paths are kept apart.
 */

/** Anchor id for a category section. Shared by the jump bar and the sections. */
const sectionId = (category: ResourceCategory) => `ghiduri-${category}`;

/**
 * The subject chip is only information when the corpus holds more than one
 * subject. Today every guide is mathematics, so eight identical "MATEMATICĂ"
 * labels would be decoration — and the design rule here is that structure
 * encodes something. This reads the manifest rather than a hardcoded answer,
 * so the chip appears by itself on the day an informatics guide lands.
 */
const SHOW_SUBJECT = new Set(RESOURCES.map((r) => r.subject)).size > 1;

/**
 * Romanian decimal comma, and KB below a megabyte — "0,6 MB" tells a student
 * less than "599 KB" does. Undefined is possible only if the generated module
 * is stale relative to the manifest, which the build guard prevents; rendering
 * nothing is still better than rendering "NaN".
 */
const formatSize = (bytes: number | undefined): string | null => {
  if (!bytes) return null;
  const kb = bytes / 1024;
  if (kb < 1024) return `${Math.round(kb)} KB`;
  return `${(kb / 1024).toFixed(1).replace('.', ',')} MB`;
};

/**
 * The file's physical facts, as a definition list rather than a run-on string
 * joined with middle dots. Each fact carries its own label for a screen
 * reader; sighted readers get the values separated by hairlines. This is the
 * bit that answers "what am I about to download" before the buttons do.
 */
const SpecStrip: React.FC<{ resource: Resource; size: string | null }> = ({ resource, size }) => {
  const specs: { label: string; value: string }[] = [{ label: 'Format', value: 'PDF' }];
  if (resource.pages) specs.push({ label: 'Întindere', value: `${resource.pages} pagini` });
  if (size) specs.push({ label: 'Mărime', value: size });

  return (
    <dl className="flex flex-wrap items-center font-mono text-[10px] md:text-[11px] tracking-[0.15em] uppercase text-[#9a9a9a]">
      {specs.map((spec, i) => (
        <div
          key={spec.label}
          className={
            i === 0
              ? 'flex items-center gap-2 pr-4'
              : 'pl-4 pr-4 border-l border-[#262626]'
          }
        >
          {i === 0 && (
            <FileText size={12} strokeWidth={2} className="shrink-0 text-[#7d7d7d]" aria-hidden />
          )}
          <dt className="sr-only">{spec.label}</dt>
          <dd className="inline whitespace-nowrap">{spec.value}</dd>
        </div>
      ))}
    </dl>
  );
};

/**
 * One guide, in its own well.
 *
 * The panel is pure black inside a #0a0a0a page, so it reads as a recess the
 * file sits in rather than a card floating above the page. The hairline is
 * what separates it; the fill alone is only a 4-point step.
 */
const ResourceCard: React.FC<{ resource: Resource; index: number }> = ({ resource, index }) => {
  const size = formatSize(resourceBytes[resource.slug]);
  const href = resourceHref(resource);

  // Every guide's actions read "Descarcă PDF" / "Citește în browser", so the
  // accessible name has to carry the title — otherwise a screen reader's link
  // list is sixteen identical entries.
  return (
    <motion.article
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.08 + index * 0.06 }}
      className="group/card bg-black border border-[#1c1c1c] hover:border-[#333] transition-colors duration-300 p-6 sm:p-8 md:p-10"
    >
      {SHOW_SUBJECT && (
        <span className="inline-block font-mono text-[10px] tracking-[0.2em] uppercase text-[#e8734a] mb-4">
          {SUBJECT_LABEL[resource.subject]}
        </span>
      )}

      <h3 className="font-display font-semibold text-[1.55rem] sm:text-3xl md:text-[2.05rem] text-[#f0f0f0] leading-[1.15] tracking-tight mb-3 text-balance">
        {resource.title}
      </h3>

      <p className="text-[0.95rem] text-[#adadad] leading-relaxed max-w-[68ch] mb-6">
        {resource.description}
      </p>

      <div className="mb-7 pb-7 border-b border-[#1c1c1c]">
        <SpecStrip resource={resource} size={size} />
      </div>

      {/* Both actions point at the same URL. The only difference is the
          `download` attribute, which is what turns a preview into a save. */}
      <div className="flex flex-col sm:flex-row gap-3">
        <a
          href={href}
          download
          aria-label={`Descarcă PDF: ${resource.title}`}
          className="inline-flex items-center justify-center gap-3 bg-[#e8734a] hover:bg-[#f08c5a] text-[#0a0a0a] px-6 py-3.5 font-mono text-[11px] tracking-[0.2em] uppercase font-medium transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08c5a] focus-visible:ring-offset-2 focus-visible:ring-offset-black"
        >
          <Download size={14} strokeWidth={2.5} className="shrink-0" aria-hidden />
          Descarcă PDF
        </a>
        <a
          href={href}
          target="_blank"
          rel="noopener"
          aria-label={`Citește în browser: ${resource.title}`}
          className="inline-flex items-center justify-center gap-3 border border-[#333] hover:border-[#e8734a]/70 text-[#ccc] hover:text-[#f0f0f0] px-6 py-3.5 font-mono text-[11px] tracking-[0.2em] uppercase font-medium transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08c5a] focus-visible:ring-offset-2 focus-visible:ring-offset-black"
        >
          Citește în browser
        </a>
      </div>
    </motion.article>
  );
};

/**
 * The jump bar. Plain anchors, so it is fully functional in the prerendered
 * HTML; the observer below only decides which one is lit. `null` until the
 * reader actually scrolls somewhere, which is also the honest prerendered
 * state — nothing is "current" before there is a scroll position.
 */
const JumpBar: React.FC<{ categories: { category: ResourceCategory; count: number }[] }> = ({
  categories,
}) => {
  const [active, setActive] = useState<ResourceCategory | null>(null);

  useEffect(() => {
    const nodes = categories
      .map(({ category }) => document.getElementById(sectionId(category)))
      .filter((n): n is HTMLElement => n !== null);
    if (!nodes.length || typeof IntersectionObserver === 'undefined') return;

    const observer = new IntersectionObserver(
      (entries) => {
        const onscreen = entries
          .filter((e) => e.isIntersecting)
          .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
        if (!onscreen.length) return;
        const id = onscreen[0].target.id;
        const match = categories.find(({ category }) => sectionId(category) === id);
        if (match) setActive(match.category);
      },
      // Top inset clears the fixed header (64px) plus this bar; the bottom
      // inset keeps a section from counting as "current" while it is only
      // peeking into the last sliver of the viewport.
      { rootMargin: '-136px 0px -55% 0px', threshold: 0 },
    );

    nodes.forEach((n) => observer.observe(n));
    return () => observer.disconnect();
  }, [categories]);

  return (
    <div className="sticky top-16 z-30 mb-12 md:mb-14 bg-[#0a0a0a]/85 backdrop-blur-xl border-y border-[#1c1c1c]">
      <nav aria-label="Secțiunile paginii" className="relative max-w-6xl mx-auto">
        <ul className="flex items-stretch gap-1 overflow-x-auto px-6 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
          {categories.map(({ category, count }) => {
            const isActive = active === category;
            return (
              <li key={category} className="shrink-0">
                <a
                  href={`#${sectionId(category)}`}
                  aria-current={isActive ? 'true' : undefined}
                  className={`flex items-center gap-2 py-3.5 px-3 font-mono text-[10px] md:text-[11px] tracking-[0.18em] uppercase whitespace-nowrap border-b-2 transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#f08c5a] focus-visible:ring-inset ${
                    isActive
                      ? 'text-[#e8734a] border-[#e8734a]'
                      : 'text-[#9a9a9a] border-transparent hover:text-[#e0e0e0]'
                  }`}
                >
                  {CATEGORY_LABEL[category]}
                  <span className={isActive ? 'text-[#e8734a]/70' : 'text-[#6f6f6f]'}>{count}</span>
                </a>
              </li>
            );
          })}
        </ul>
        {/* Signals that the bar scrolls on a narrow screen. Decorative only. */}
        <span
          aria-hidden
          className="md:hidden pointer-events-none absolute right-0 top-0 bottom-0 w-10 bg-gradient-to-l from-[#0a0a0a] to-transparent"
        />
      </nav>
    </div>
  );
};

const Resources: React.FC = () => {
  const count = RESOURCES.length;

  const sections = CATEGORY_ORDER.map((category) => ({
    category,
    items: resourcesForCategory(category),
  })).filter((s) => s.items.length > 0);

  return (
    <PageTransition>
      <SEO
        title="Resurse gratuite — ghiduri de matematică pentru BAC, Evaluarea Națională și gimnaziu | AlgoMate"
        description="Ghiduri gratuite în PDF la matematică — Bacalaureat M1, Evaluarea Națională și materia de gimnaziu, clasele a V-a și a VII-a: teorie esențială, probleme rezolvate pas cu pas și modele de subiect. Fără cont și fără adresă de e-mail."
        path="/resurse"
        jsonLd={breadcrumbSchema([{ name: 'Resurse', path: '/resurse' }])}
      />
      <div className="min-h-screen text-[#f0f0f0] pt-24 md:pt-28 pb-20 md:pb-24">
        <div className="max-w-6xl mx-auto px-6">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="mb-12 md:mb-14"
          >
            <div className="flex items-baseline gap-3 md:gap-4 mb-6 md:mb-8">
              <span className="font-mono text-[10px] md:text-[11px] tracking-[0.2em] md:tracking-[0.3em] text-[#e8734a] uppercase whitespace-nowrap">
                § AlgoMate / Resurse
              </span>
              <span className="h-px flex-1 bg-gradient-to-r from-[#333] via-[#222] to-transparent" />
              <span className="font-mono text-[10px] md:text-[11px] tracking-[0.25em] md:tracking-[0.3em] text-[#8a8a8a] uppercase hidden md:inline">
                {count} {count === 1 ? 'ghid' : 'ghiduri'}
              </span>
            </div>

            <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-5 md:gap-6">
              <h1 className="font-display font-semibold text-[3rem] sm:text-6xl md:text-7xl text-[#f0f0f0] leading-[1.02] tracking-tight">
                Resurse<em className="italic text-[#e8734a] font-normal">.</em>
              </h1>
              <p className="font-mono text-[11px] md:text-xs text-[#9a9a9a] md:max-w-xs uppercase tracking-wider leading-relaxed">
                → Ghiduri complete, pe subiecte, în PDF.
              </p>
            </div>
          </motion.div>

          {/* The terms and the mechanics, stated once. Nothing here asks for an
              e-mail address, and the two ways to open a guide are named before
              the reader meets the first pair of buttons. */}
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.15 }}
            className="max-w-2xl text-[0.98rem] leading-relaxed text-[#adadad] mb-10 md:mb-12"
          >
            Ghidurile sunt gratuite și se deschid direct — fără cont, fără formular și fără
            adresă de e-mail. Pe fiecare ai două variante:{' '}
            <span className="text-[#f0f0f0]">citește-l în browser</span>, dacă vrei doar să
            arunci un ochi, sau{' '}
            <span className="text-[#f0f0f0]">descarcă-l ca PDF</span>, ca să-l ai la tine și
            offline.
          </motion.p>
        </div>

        {count === 0 ? (
          <div className="max-w-6xl mx-auto px-6">
            <div className="border-y border-[#222] py-20 text-center">
              <p className="text-lg text-[#9a9a9a]">Primele materiale sunt în pregătire.</p>
              <Link
                to="/blog"
                className="group/link inline-flex items-center gap-3 mt-8 font-mono text-[10px] tracking-[0.3em] uppercase text-[#e8734a] pb-2 border-b border-[#e8734a]/20 hover:border-[#e8734a]/80 transition-all duration-300"
              >
                Între timp, citește subiectele rezolvate
                <ArrowRight
                  size={12}
                  strokeWidth={2.5}
                  className="group-hover/link:translate-x-1 transition-transform"
                />
              </Link>
            </div>
          </div>
        ) : (
          <>
            <JumpBar
              categories={sections.map((s) => ({
                category: s.category,
                count: s.items.length,
              }))}
            />

            <div className="max-w-6xl mx-auto px-6">
              {sections.map(({ category, items }) => (
                <section
                  key={category}
                  id={sectionId(category)}
                  aria-labelledby={`${sectionId(category)}-titlu`}
                  className="scroll-mt-[8.5rem] mb-14 md:mb-18 last:mb-0"
                >
                  <div className="flex items-baseline gap-4 mb-5 md:mb-6">
                    <h2
                      id={`${sectionId(category)}-titlu`}
                      className="font-mono text-[11px] md:text-xs tracking-[0.3em] uppercase text-[#cfcfcf]"
                    >
                      {CATEGORY_LABEL[category]}
                    </h2>
                    <span className="h-px flex-1 bg-[#222]" />
                    <span className="font-mono text-[10px] tracking-[0.25em] uppercase text-[#8a8a8a]">
                      {items.length} {items.length === 1 ? 'ghid' : 'ghiduri'}
                    </span>
                  </div>

                  <div className="flex flex-col gap-4 md:gap-5">
                    {items.map((resource, idx) => (
                      <ResourceCard key={resource.slug} resource={resource} index={idx} />
                    ))}
                  </div>
                </section>
              ))}
            </div>
          </>
        )}

        <div className="max-w-6xl mx-auto px-6">
          {/* Closing CTA — the page is free material, but it is also the top of
              the funnel for the thing that is not free. */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="mt-20 md:mt-24 border-t border-[#222] pt-10 flex flex-col md:flex-row md:items-end md:justify-between gap-6"
          >
            <p className="max-w-xl text-[0.98rem] leading-relaxed text-[#adadad]">
              Ghidurile acoperă teoria și exercițiile de bază. Pentru explicații pe punctele
              unde te blochezi și pentru un plan de pregătire pe măsura examenului tău, vino la
              o ședință.
            </p>
            <Link
              to="/inscriere"
              className="group/link inline-flex items-center gap-3 font-mono text-[10px] tracking-[0.3em] uppercase text-[#e8734a] pb-2 border-b border-[#e8734a]/20 hover:border-[#e8734a]/80 transition-all duration-300 whitespace-nowrap self-start md:self-auto"
            >
              Rezervă o ședință
              <ArrowRight
                size={12}
                strokeWidth={2.5}
                className="group-hover/link:translate-x-1 transition-transform"
              />
            </Link>
          </motion.div>
        </div>
      </div>
    </PageTransition>
  );
};

export default Resources;
