import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowRight, Download } from 'lucide-react';
import PageTransition from '../components/PageTransition';
import SEO from '../components/SEO';
import { breadcrumbSchema } from '../seo/structuredData';
import {
  CATEGORY_LABEL,
  CATEGORY_ORDER,
  RESOURCES,
  SUBJECT_LABEL,
  resourceHref,
  resourcesForCategory,
} from '../config/resources';
import type { Resource } from '../config/resources';
import { resourceBytes } from '../content/resources.generated';

/**
 * /resurse — the downloads listing.
 *
 * Two things about this page are deliberate and easy to undo by accident.
 *
 * NO FILTER STATE. The materials are grouped into static sections by
 * category rather than filtered in React. The site is prerendered with Playwright, and
 * a filter that unmounts non-matching entries would bake only the default
 * subset into the HTML a crawler reads — the same failure that shipped six
 * missing FAQ answers to production. Every entry is in the DOM on first paint,
 * unconditionally. If filtering is ever added, hide with CSS, never unmount.
 *
 * NO HAND-TYPED SIZES. `resourceBytes` is generated by build-content.mjs from
 * the files themselves; a size here can never disagree with what downloads.
 *
 * The files are served from /descarcari/, not from under /resurse — see
 * docs/DOWNLOADS-SECTION.md §3.1 for why the two paths are kept apart.
 */

/**
 * Romanian decimal comma, and KB below a megabyte — "0,4 MB" tells a student
 * less than "418 KB" does. Undefined is possible only if the generated module
 * is stale relative to the manifest, which the build guard prevents; rendering
 * nothing is still better than rendering "NaN".
 */
const formatSize = (bytes: number | undefined): string | null => {
  if (!bytes) return null;
  const kb = bytes / 1024;
  if (kb < 1024) return `${Math.round(kb)} KB`;
  return `${(kb / 1024).toFixed(1).replace('.', ',')} MB`;
};

/**
 * `download` on a same-origin anchor saves the file instead of opening the
 * browser's PDF viewer. Pasting the URL straight into a tab still previews it,
 * which is the friendlier behaviour for a shared link — and is exactly why the
 * server does not send Content-Disposition: attachment, which would force a
 * save in every context.
 */
const ResourceRow: React.FC<{ resource: Resource; index: number }> = ({ resource, index }) => {
  const size = formatSize(resourceBytes[resource.slug]);

  return (
    <motion.article
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.1 + index * 0.06 }}
      className="border-b border-[#222]"
    >
      <a
        href={resourceHref(resource)}
        download
        className="group block py-8 md:py-9 hover:bg-[#111]/60 transition-colors duration-500 -mx-4 px-4 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#e8734a]"
      >
        <div className="grid grid-cols-1 md:grid-cols-12 gap-4 md:gap-8 items-baseline">
          {/* Margin metadata — what a student sorts on before the title. */}
          <div className="md:col-span-3 flex md:flex-col gap-4 md:gap-2">
            <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#e8734a]">
              {SUBJECT_LABEL[resource.subject]}
            </span>
            <span className="font-mono text-[10px] tracking-[0.2em] uppercase text-[#666]">
              PDF
              {resource.pages ? ` · ${resource.pages} pag.` : ''}
              {size ? ` · ${size}` : ''}
            </span>
          </div>

          {/* Title + description */}
          <div className="md:col-span-7">
            <h3 className="font-display font-semibold text-2xl sm:text-3xl md:text-[2rem] text-[#f0f0f0] leading-[1.15] tracking-tight mb-3 group-hover:text-white transition-colors">
              {resource.title}
            </h3>
            <p className="text-[0.95rem] text-[#999] leading-relaxed max-w-2xl">
              {resource.description}
            </p>
          </div>

          {/* The affordance. The whole row is the link; this is what says so. */}
          <div className="md:col-span-2 md:text-right">
            <span className="inline-flex items-center gap-2 font-mono text-[10px] tracking-[0.2em] uppercase text-[#888] group-hover:text-[#e8734a] transition-colors whitespace-nowrap">
              <Download size={13} strokeWidth={2} className="shrink-0" />
              Descarcă
            </span>
          </div>
        </div>
      </a>
    </motion.article>
  );
};

const Resources: React.FC = () => {
  const count = RESOURCES.length;

  return (
    <PageTransition>
      <SEO
        title="Resurse gratuite — ghiduri de matematică pentru BAC, Evaluarea Națională și gimnaziu | AlgoMate"
        description="Ghiduri gratuite în PDF la matematică — Bacalaureat M1, Evaluarea Națională și materia de clasa a VII-a: teorie esențială, probleme rezolvate pas cu pas și modele de subiect. Fără cont și fără adresă de e-mail."
        path="/resurse"
        jsonLd={breadcrumbSchema([{ name: 'Resurse', path: '/resurse' }])}
      />
      <div className="min-h-screen text-[#f0f0f0] pt-24 md:pt-28 pb-20 md:pb-24">
        <div className="max-w-6xl mx-auto px-6">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
            className="mb-14 md:mb-16"
          >
            <div className="flex items-baseline gap-3 md:gap-4 mb-6 md:mb-8">
              <span className="font-mono text-[10px] md:text-[11px] tracking-[0.2em] md:tracking-[0.3em] text-[#e8734a] uppercase whitespace-nowrap">
                § AlgoMate / Resurse
              </span>
              <span className="h-px flex-1 bg-gradient-to-r from-[#333] via-[#222] to-transparent" />
              <span className="font-mono text-[10px] md:text-[11px] tracking-[0.25em] md:tracking-[0.3em] text-[#666] uppercase hidden md:inline">
                {count} {count === 1 ? 'material' : 'materiale'}
              </span>
            </div>

            <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-5 md:gap-6">
              <h1 className="font-display font-semibold text-[3rem] sm:text-6xl md:text-7xl text-[#f0f0f0] leading-[1.02] tracking-tight">
                Resurse<em className="italic text-[#e8734a] font-normal">.</em>
              </h1>
              <p className="font-mono text-[11px] md:text-xs text-[#888] md:max-w-xs uppercase tracking-wider leading-relaxed">
                → Ghiduri complete, pe subiecte, în PDF.
              </p>
            </div>
          </motion.div>

          {/* The terms, stated once and plainly. Nothing here asks for an
              e-mail address, and the copy should not imply otherwise. */}
          <motion.p
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.15 }}
            className="max-w-2xl text-[0.98rem] leading-relaxed text-[#999] mb-14 md:mb-16"
          >
            Materialele de mai jos sunt gratuite și se descarcă direct — fără cont, fără
            formular și fără adresă de e-mail. Le folosesc la ședințe și le poți folosi și
            singur, pentru recapitulare sau pentru exersare între ore.
          </motion.p>

          {count === 0 ? (
            <div className="border-y border-[#222] py-20 text-center">
              <p className="text-lg text-[#999]">Primele materiale sunt în pregătire.</p>
              <Link
                to="/blog"
                className="group/link inline-flex items-center gap-3 mt-8 font-mono text-[10px] tracking-[0.3em] uppercase text-[#e8734a] pb-2 border-b border-[#e8734a]/20 hover:border-[#e8734a]/80 transition-all duration-300"
              >
                Între timp, citește subiectele rezolvate
                <ArrowRight
                  size={12}
                  strokeWidth={2.5}
                  className="group-hover/link:translate-x-1 transition-transform"
                />
              </Link>
            </div>
          ) : (
            CATEGORY_ORDER.map((category) => {
              const items = resourcesForCategory(category);
              if (!items.length) return null;

              return (
                <section key={category} className="mb-16 md:mb-20 last:mb-0">
                  <div className="flex items-baseline gap-4 mb-2">
                    <h2 className="font-mono text-[11px] tracking-[0.3em] uppercase text-[#888]">
                      {CATEGORY_LABEL[category]}
                    </h2>
                    <span className="h-px flex-1 bg-[#222]" />
                    <span className="font-mono text-[10px] tracking-[0.25em] uppercase text-[#555]">
                      {items.length}
                    </span>
                  </div>

                  <div className="border-t border-[#222]">
                    {items.map((resource, idx) => (
                      <ResourceRow key={resource.slug} resource={resource} index={idx} />
                    ))}
                  </div>
                </section>
              );
            })
          )}

          {/* Closing CTA — the page is free material, but it is also the top of
              the funnel for the thing that is not free. */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="mt-20 md:mt-24 border-t border-[#222] pt-10 flex flex-col md:flex-row md:items-end md:justify-between gap-6"
          >
            <p className="max-w-xl text-[0.98rem] leading-relaxed text-[#999]">
              Materialele acoperă teoria și exercițiile de bază. Pentru explicații pe punctele
              unde te blochezi și pentru un plan de pregătire pe măsura examenului tău, vino la
              o ședință.
            </p>
            <Link
              to="/inscriere"
              className="group/link inline-flex items-center gap-3 font-mono text-[10px] tracking-[0.3em] uppercase text-[#e8734a] pb-2 border-b border-[#e8734a]/20 hover:border-[#e8734a]/80 transition-all duration-300 whitespace-nowrap self-start md:self-auto"
            >
              Rezervă o ședință
              <ArrowRight
                size={12}
                strokeWidth={2.5}
                className="group-hover/link:translate-x-1 transition-transform"
              />
            </Link>
          </motion.div>
        </div>
      </div>
    </PageTransition>
  );
};

export default Resources;
